# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "F# Reflections"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Blog about F# and FP Programming"

# Tagline near the site title
tagline: "Thoughts, stories and ideas."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://kcieslak.io"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "Krzysztof Cieslak"
author_bio: "Krzysztof is a F# developer and consultant, open source contributor, conference speaker"
author_url:  "http://kcieslak.io"
author_location: "Lodz, Poland"
author_image: /images/authorimage.jpg

# Sidebar Add banner
banner_url: "http://lambdafactory.io"
banner_image: images/banner.png

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
# "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"
# mailchimp_url: 

# Analytics and webmaster tools stuff goes here
google_analytics: UA-74514389-1

# Social links in the site footer
twitter_username: "k_cieslak"
github_username: "Krzysztof-Cieslak"
email: krzysztof_cieslak@windowslive.com


# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]

permalink: /:title
markdown: kramdown
kramdown:
    auto_ids: false 
    syntax_highlighter: nil

exclude: ["packages", "build.*", "paket.*", "temp"]
